spring:

  datasource:
    username: uzck
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todo?useUnicode=true&characterEncoding=UTF-8
  freemarker:
    charset: UTF-8
    cache: false
    template-loader-path: classpath:/templates/
    suffix: .ftl

mybatis:
  type-aliases-package: security/dao
  mapper-locations: classpath:mapper/*.xml

